swagger: "2.0"

info:
  title: dp-search-reindex-api
  description: "Provides details about search reindex jobs and enables creation and running of them"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"

basePath: "/v1"

schemes:
  - http

tags:
  - name: "search-reindex"

paths:

  /jobs/{id}:
    get:
      description: Get a specific job.
      parameters:
        - $ref: '#/parameters/id'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Job"
        500:
          $ref: '#/responses/InternalError'

  /jobs:
    get:
      description: Get a list of jobs.
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/sort'
        - $ref: '#/parameters/state'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Jobs"
        500:
          $ref: '#/responses/InternalError'

responses:

  InternalError:
    description: "Failed to process the request due to an internal error"

definitions:

  Job:
    type: object
    properties:
      id:
        type: string
      last_updated:
        type: string
        format: date
        description: ISO8601 timestamp
      links:
        type: object
        properties:
          tasks:
            type: string
            format: http://localhost:<port>/jobs/{id}/tasks
          self:
            type: string
            format: http://localhost:<port>/jobs/{id}
      number_of_tasks:
        type: integer
      reindex_completed:
        type: string
        format: date
        description: ISO8601 timestamp
      reindex_failed:
        type: string
        format: date
        description: ISO8601 timestamp
      reindex_started:
        type: string
        format: date
        description: ISO8601 timestamp
      search_index_name:
        type: string
      state:
        type: string
        enum:
          - CREATED
          - IN-PROGRESS
          - COMPLETED
          - FAILED
      total_search_documents:
        type: integer

  Jobs:
    type: object
    properties:
      count:
        type: integer
      items:
        type: array
        items:
          $ref: '#/definitions/Job'
      limit:
        type: integer
      offset:
        type: integer
      total_count:
        type: integer
      sort:
        type: integer

parameters:

  id:
    name: id
    description: The id of a search reindex job when job POSTed (Job.id)
    in: path
    required: true
    type: string

  limit:
    name: limit
    description: The maximum number of Job objects we're returning in this Jobs object
    in: query
    type: integer

  offset:
    name: offset
    description: The number of Job objects into the full list that this particular response is starting at
    in: query
    type: integer

  sort:
    name: sort
    description: Sort on last_updated field
    in: query
    type: boolean

  state:
    name: state
    description: Filter option to bring back specific Job objects according to their state
    in: query
    type: string
    enum:
      - CREATED
      - IN-PROGRESS
      - COMPLETED
      - FAILED
