swagger: "2.0"

info:
  title: dp-search-reindex-api
  description: "Provides details about search reindex jobs and enables creation and running of them"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"

basePath: "/v1"

schemes:
  - http

tags:
  - name: "Public"

paths:

  /jobs/{id}:
    get:
      tags:
        - "Public"
      summary: Get a specific job.
      description: Get the specific search reindex job that has the id given in the path.
      parameters:
        - $ref: '#/parameters/id'
      produces:
        - application/json
      responses:
        200:
          description: Successfully returned a job for the given id
          schema:
            $ref: "#/definitions/Job"
        500:
          $ref: '#/responses/InternalError'
        404:
          $ref: '#/responses/ResourceNotFound'

  /jobs:
    get:
      tags:
        - "Public"
      summary: Get a list of jobs.
      description: Get a list of search reindex jobs that meet the criteria specified by the four query parameters.
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/sort'
        - $ref: '#/parameters/state'
      produces:
        - application/json
      responses:
        200:
          description: Successfully returned the requested list of jobs.
          schema:
            $ref: "#/definitions/Jobs"
        400:
          $ref: '#/responses/InvalidRequest'
        500:
          $ref: '#/responses/InternalError'
    post:
      tags:
        - "Public"
      summary: Create a new search reindex job.
      description: Post details of a new search reindex job and receive the new Job object created in response.
      parameters:
        - $ref: '#/parameters/job'
      produces:
        - application/json
      responses:
        201:
          description: Successfully created a new search reindex job.
          schema:
            $ref: "#/definitions/Job"
        400:
          $ref: '#/responses/InvalidRequest'
        500:
          $ref: '#/responses/InternalError'

responses:

  InternalError:
    description: "Failed to process the request due to an internal error"

  ResourceNotFound:
    description: "Failed to locate a Job that has the specified id"

  InvalidRequest:
    description: "The request does not contain the correct parameters and/or values in its parameters"

definitions:

  Job:
    type: object
    required:
      - "id"
      - "last_updated"
      - "links"
      - "search_index_name"
      - "state"
    properties:
      id:
        type: string
      last_updated:
        type: string
        format: date-time
        description: ISO8601 timestamp
      links:
        type: object
        required:
          - "tasks"
          - "self"
        properties:
          tasks:
            type: string
            format: http://localhost:<port>/jobs/{id}/tasks
            example: http://localhost:12150/jobs/abc123/tasks
          self:
            type: string
            format: http://localhost:<port>/jobs/{id}
            example: http://localhost:12150/jobs/abc123
      number_of_tasks:
        type: integer
      reindex_completed:
        type: string
        format: date-time
        description: ISO8601 timestamp - The date and time when the reindex job was completed.
      reindex_failed:
        type: string
        format: date-time
        description: ISO8601 timestamp - The date and time when the reindex job failed.
      reindex_started:
        type: string
        format: date-time
        description: ISO8601 timestamp - The date and time when the reindex job was started.
      search_index_name:
        type: string
      state:
        type: string
        enum:
          - CREATED
          - IN-PROGRESS
          - COMPLETED
          - FAILED
      total_search_documents:
        type: integer

  NewJob:
    type: object
    required:
      - "last_updated"
      - "search_index_name"
      - "state"
    properties:
      last_updated:
        type: string
        format: date
        description: ISO8601 timestamp - The last date and time that the information about this reindex job was updated.
      number_of_tasks:
        type: integer
      reindex_completed:
        type: string
        format: date
        description: ISO8601 timestamp - The date and time when the reindex job was completed.
      reindex_failed:
        type: string
        format: date
        description: ISO8601 timestamp - The date and time when the reindex job failed.
      reindex_started:
        type: string
        format: date
        description: ISO8601 timestamp - The date and time when the reindex job was started.
      search_index_name:
        type: string
      state:
        type: string
        enum:
          - CREATED
          - IN-PROGRESS
          - COMPLETED
          - FAILED
      total_search_documents:
        type: integer

  Jobs:
    type: object
    required:
      - "count"
      - "items"
      - "limit"
      - "offset"
      - "total_count"
    properties:
      count:
        type: integer
      items:
        type: array
        items:
          $ref: '#/definitions/Job'
      limit:
        type: integer
      offset:
        type: integer
      total_count:
        type: integer
      sort:
        type: integer

parameters:

  id:
    name: id
    description: The id of a search reindex job (Job.id)
    in: path
    required: true
    type: string

  limit:
    name: limit
    description: The maximum number of Job objects we're returning in this Jobs object. The default limit is 20.
    in: query
    type: integer
    default: 20

  offset:
    name: offset
    description: The number of Job objects into the full list that this particular response is starting at. The default number to start at is 0.
    in: query
    type: integer
    default: 0

  sort:
    name: sort
    description: Sort on last_updated field
    in: query
    type: boolean

  state:
    name: state
    description: Filter option to bring back specific Job objects according to their state
    in: query
    type: string
    enum:
      - CREATED
      - IN-PROGRESS
      - COMPLETED
      - FAILED

  job:
    name: job
    description: Details of a Job object, to POST, without id and links as these are generated by the application
    in: body
    required: true
    schema:
      $ref: '#/definitions/NewJob'

