---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.21.3-bullseye

inputs:
  - name: dp-search-reindex-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-search-reindex-api/ci/scripts/build.sh
